1. What is a Python library? Why do we use Python libraries?

Ans : A python library is collection of functions, classes and variables that  
      can be use to perform specific task. In python library is collection of releted modules that cantain reusable code for various purposes and features.
          we use python librarise to make programming simpler and more convenint as we don't have to write the same code again and again for different programs. python libraries also provide access to system functionality.some examples of python libraries are NumPy, Pandas, Matplotlib, TraansorFlow,etc.

2. What is the difference between Numpy array and List?

Ans : A Numpy array is collection of homogeneous data, which means all the elements have the same data type.
      A List is collection of hetrogeneous data, which means the elements have differrent data types is single List.
      A Numpy array ha sfixed size and data types, which makes it more memory-efficient and fassster for numerical operations than a List.
     A List can change its size and data types dynamically , which gives it more flexibility but also more overhead.





3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr
shape = np.shape(arr)
size = np.size(arr)
dimen = arr.ndim
print("Shape of array is : ",shape)
print("Size of array is : ",size)
print("Dimension of array is : ",dimen)

Shape of array is :  (3, 4)
Size of array is :  12
Dimension of array is :  2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[1::2]

array([[5, 6, 7, 8]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [ ]:
import random
arr = np.random.randint(0,2 ,(3,3))
arr

array([[0, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

8. Describe the difference between np.random.rand and np.random.randn?

The difference between np.random.rand and np.random.randn is that np.random.rand generates random numbers from a uniform distribution over the interval [0, 1), while np.random.randn generates random numbers from a normal distribution with a mean of 0 and a variance of 1. This means that the numbers produced by np.random.rand are equally likely to fall anywhere in the range [0, 1), while the numbers produced by np.random.randn are more likely to be close to 0 and less likely to be very large or very small.

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("original array :\n",arr)
arr1 = np.expand_dims(arr, axis=0)
print("After increasing dimension :\n ",arr1)

original array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After increasing dimension :
  [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 1.Index wise multiplication
arr1 * arr2

which function in numpy can be used to swap the byte order of an array?

There are two common byte orders: Little-endian: Least significant byte comes first in memory. Big-endian: Most significant byte comes first in memory. Usage: The byteswap () method takes an optional inplace argument: inplace=False (default): Returns a new array with swapped byte order, leaving the original array intact.

 13.  What is the significance of the np.linalg.inv function?


The numpy.linalg.inv () function is extremely helpful when doing rigorous calculations. Knowing the correct syntax and modifying the code to accommodate user input helps when there is no static input for a particular program. The numpy library contains many such other functions which make the life of a programmer easier.


 14. What does the np.reshape function do, and how is it used?


The numpy.reshape () function is useful when we need to change the dimensions of an array, for example, when we want to convert a one-dimensional array into a two-dimensional array or vice versa. It can also be used to create arrays with a specific shape, such as matrices and tensors.

 15. What is broadcasting in Numpy?


The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic operations. This process involves certain rules that allow the smaller array to be ‘broadcast’ across the larger one, ensuring that they have compatible shapes for these operations.

Broadcasting is not limited to two arrays; it can be applied over multiple arrays as well.